title:              SolutionVaults
email:              solutionvaults@gmail.com
description:        With Words, Power is Lost With Repetition, Meaning is Lost With Scarcity
author:             ambuba
baseurl:            "/"
url:                "https://startbootstrap.github.io"
theme:              jekyll-theme-clean-blog

# Social Profiles
twitter_username:   @AntonyMbuba
github_username:    solutionvaults
facebook_username:  Antony Ireri Mbuba
instagram_username: mwongerat
linkedin_username:  antonyirerimbuba

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-XGPW616BBL # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
